{{- if .Values.service.tls.enabled }}
{{- $ca := genCA "nginx-ca" 365 }}
{{- $cert := genSignedCert .Values.service.tls.hostname nil (list .Values.service.tls.hostname) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-tls" .Values.service.tls.hostname }}
  labels: 
      app.kubernetes.io/name: {{.Chart.Name}}
      helm.sh/chart: {{.Chart.Name}}-{{.Chart.Version}}
      app.kubernetes.io/instance: {{.Release.Name}}
      app.kubernetes.io/managed-by: Helm
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
{{- end }}